# Generated by Django 6.0.7 on 2026-08-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_translation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='segment',
            field=models.CharField(choices=[('grand_public', 'Grand public'), ('entreprise', 'Entreprise')], default='grand_public', max_length=20),
        ),
    ]
