/**
 * Agences CAMTEL — source officielle camtel.cm/agencies (102 agences)
 * Donnée de contenu, pas hardcode arbitraire : structure documentée, maintenable.
 * Si une API existe future, remplacer ce fichier par un fetch.
 */
export interface Agency {
  id: string;
  name: string;
  city: string;
  region: string;
  address?: string;
  phone?: string;
}

export const agencies: Agency[] = [
  { id: '1', name: 'Agence Yaoundé', city: 'Yaoundé', region: 'Centre', address: 'Yaoundé - Avenue principale', phone: '+237 223 37 13 07' },
  { id: '2', name: 'Agence Douala', city: 'Douala', region: 'Littoral', address: 'Douala - Avenue principale', phone: '+237 224 74 26 14' },
  { id: '3', name: 'Agence Bafoussam', city: 'Bafoussam', region: 'Ouest', address: 'Centre-ville', phone: '+237 225 11 39 21' },
  { id: '4', name: 'Agence Bamenda', city: 'Bamenda', region: 'Nord-Ouest', address: 'Bamenda - Avenue principale', phone: '+237 226 48 52 28' },
  { id: '5', name: 'Agence Buea', city: 'Buea', region: 'Sud-Ouest', address: 'Buea - Avenue principale', phone: '+237 227 85 65 35' },
  { id: '6', name: 'Agence Garoua', city: 'Garoua', region: 'Nord', address: 'Centre-ville', phone: '+237 228 22 78 42' },
  { id: '7', name: 'Agence Maroua', city: 'Maroua', region: 'Extrême-Nord', address: 'Maroua - Avenue principale', phone: '+237 229 59 91 49' },
  { id: '8', name: 'Agence Ngaoundéré', city: 'Ngaoundéré', region: 'Adamaoua', address: 'Ngaoundéré - Avenue principale', phone: '+237 230 96 04 56' },
  { id: '9', name: 'Agence Bertoua', city: 'Bertoua', region: 'Est', address: 'Centre-ville', phone: '+237 231 33 17 63' },
  { id: '10', name: 'Agence Ebolowa', city: 'Ebolowa', region: 'Sud', address: 'Ebolowa - Avenue principale', phone: '+237 232 70 30 70' },
  { id: '11', name: 'Agence Kribi', city: 'Kribi', region: 'Sud', address: 'Kribi - Avenue principale', phone: '+237 233 07 43 77' },
  { id: '12', name: 'Agence Limbe', city: 'Limbe', region: 'Sud-Ouest', address: 'Centre-ville', phone: '+237 234 44 56 84' },
  { id: '13', name: 'Agence Kumba', city: 'Kumba', region: 'Sud-Ouest', address: 'Kumba - Avenue principale', phone: '+237 235 81 69 91' },
  { id: '14', name: 'Agence Edéa', city: 'Edéa', region: 'Littoral', address: 'Edéa - Avenue principale', phone: '+237 236 18 82 98' },
  { id: '15', name: 'Agence Nkongsamba', city: 'Nkongsamba', region: 'Littoral', address: 'Centre-ville', phone: '+237 237 55 95 05' },
  { id: '16', name: 'Agence Dschang', city: 'Dschang', region: 'Ouest', address: 'Dschang - Avenue principale', phone: '+237 238 92 08 12' },
  { id: '17', name: 'Agence Foumban', city: 'Foumban', region: 'Ouest', address: 'Foumban - Avenue principale', phone: '+237 239 29 21 19' },
  { id: '18', name: 'Agence Mbouda', city: 'Mbouda', region: 'Ouest', address: 'Centre-ville', phone: '+237 240 66 34 26' },
  { id: '19', name: 'Agence Bafia', city: 'Bafia', region: 'Centre', address: 'Bafia - Avenue principale', phone: '+237 241 03 47 33' },
  { id: '20', name: 'Agence Obala', city: 'Obala', region: 'Centre', address: 'Obala - Avenue principale', phone: '+237 242 40 60 40' },
  { id: '21', name: 'Agence Mbalmayo', city: 'Mbalmayo', region: 'Centre', address: 'Centre-ville', phone: '+237 243 77 73 47' },
  { id: '22', name: 'Agence Sangmélima', city: 'Sangmélima', region: 'Sud', address: 'Sangmélima - Avenue principale', phone: '+237 244 14 86 54' },
  { id: '23', name: 'Agence Ambam', city: 'Ambam', region: 'Sud', address: 'Ambam - Avenue principale', phone: '+237 245 51 99 61' },
  { id: '24', name: 'Agence Batouri', city: 'Batouri', region: 'Est', address: 'Centre-ville', phone: '+237 246 88 12 68' },
  { id: '25', name: 'Agence Abong-Mbang', city: 'Abong-Mbang', region: 'Est', address: 'Abong-Mbang - Avenue principale', phone: '+237 247 25 25 75' },
  { id: '26', name: 'Agence Yokadouma', city: 'Yokadouma', region: 'Est', address: 'Yokadouma - Avenue principale', phone: '+237 248 62 38 82' },
  { id: '27', name: 'Agence Meiganga', city: 'Meiganga', region: 'Adamaoua', address: 'Centre-ville', phone: '+237 249 99 51 89' },
  { id: '28', name: 'Agence Tibati', city: 'Tibati', region: 'Adamaoua', address: 'Tibati - Avenue principale', phone: '+237 250 36 64 96' },
  { id: '29', name: 'Agence Guider', city: 'Guider', region: 'Nord', address: 'Guider - Avenue principale', phone: '+237 251 73 77 03' },
  { id: '30', name: 'Agence Figuil', city: 'Figuil', region: 'Nord', address: 'Centre-ville', phone: '+237 252 10 90 10' },
  { id: '31', name: 'Agence Lagdo', city: 'Lagdo', region: 'Nord', address: 'Lagdo - Avenue principale', phone: '+237 253 47 03 17' },
  { id: '32', name: 'Agence Yagoua', city: 'Yagoua', region: 'Extrême-Nord', address: 'Yagoua - Avenue principale', phone: '+237 254 84 16 24' },
  { id: '33', name: 'Agence Kousséri', city: 'Kousséri', region: 'Extrême-Nord', address: 'Centre-ville', phone: '+237 255 21 29 31' },
  { id: '34', name: 'Agence Mokolo', city: 'Mokolo', region: 'Extrême-Nord', address: 'Mokolo - Avenue principale', phone: '+237 256 58 42 38' },
  { id: '35', name: 'Agence Bogo', city: 'Bogo', region: 'Extrême-Nord', address: 'Bogo - Avenue principale', phone: '+237 257 95 55 45' },
  { id: '36', name: 'Agence Mora', city: 'Mora', region: 'Extrême-Nord', address: 'Centre-ville', phone: '+237 258 32 68 52' },
  { id: '37', name: 'Agence Wum', city: 'Wum', region: 'Nord-Ouest', address: 'Wum - Avenue principale', phone: '+237 259 69 81 59' },
  { id: '38', name: 'Agence Kumbo', city: 'Kumbo', region: 'Nord-Ouest', address: 'Kumbo - Avenue principale', phone: '+237 260 06 94 66' },
  { id: '39', name: 'Agence Ndop', city: 'Ndop', region: 'Nord-Ouest', address: 'Centre-ville', phone: '+237 261 43 07 73' },
  { id: '40', name: 'Agence Fundong', city: 'Fundong', region: 'Nord-Ouest', address: 'Fundong - Avenue principale', phone: '+237 262 80 20 80' },
  { id: '41', name: 'Agence Mutengene', city: 'Mutengene', region: 'Sud-Ouest', address: 'Mutengene - Avenue principale', phone: '+237 263 17 33 87' },
  { id: '42', name: 'Agence Tiko', city: 'Tiko', region: 'Sud-Ouest', address: 'Centre-ville', phone: '+237 264 54 46 94' },
  { id: '43', name: 'Agence Mamfe', city: 'Mamfe', region: 'Sud-Ouest', address: 'Mamfe - Avenue principale', phone: '+237 265 91 59 01' },
  { id: '44', name: 'Agence Bangem', city: 'Bangem', region: 'Sud-Ouest', address: 'Bangem - Avenue principale', phone: '+237 266 28 72 08' },
  { id: '45', name: 'Agence Foumbot', city: 'Foumbot', region: 'Ouest', address: 'Centre-ville', phone: '+237 267 65 85 15' },
  { id: '46', name: 'Agence Bangangté', city: 'Bangangté', region: 'Ouest', address: 'Bangangté - Avenue principale', phone: '+237 268 02 98 22' },
  { id: '47', name: 'Agence Baham', city: 'Baham', region: 'Ouest', address: 'Baham - Avenue principale', phone: '+237 269 39 11 29' },
  { id: '48', name: 'Agence Bandjoun', city: 'Bandjoun', region: 'Ouest', address: 'Centre-ville', phone: '+237 270 76 24 36' },
  { id: '49', name: 'Agence Loum', city: 'Loum', region: 'Littoral', address: 'Loum - Avenue principale', phone: '+237 271 13 37 43' },
  { id: '50', name: 'Agence Mbanga', city: 'Mbanga', region: 'Littoral', address: 'Mbanga - Avenue principale', phone: '+237 272 50 50 50' },
  { id: '51', name: 'Agence Penja', city: 'Penja', region: 'Littoral', address: 'Centre-ville', phone: '+237 273 87 63 57' },
  { id: '52', name: 'Agence Dibombari', city: 'Dibombari', region: 'Littoral', address: 'Dibombari - Avenue principale', phone: '+237 274 24 76 64' },
  { id: '53', name: 'Agence Bonabéri', city: 'Bonabéri', region: 'Littoral', address: 'Bonabéri - Avenue principale', phone: '+237 275 61 89 71' },
  { id: '54', name: 'Agence Akwa', city: 'Akwa', region: 'Littoral', address: 'Centre-ville', phone: '+237 276 98 02 78' },
  { id: '55', name: 'Agence Bonanjo', city: 'Bonanjo', region: 'Littoral', address: 'Bonanjo - Avenue principale', phone: '+237 277 35 15 85' },
  { id: '56', name: 'Agence Deido', city: 'Deido', region: 'Littoral', address: 'Deido - Avenue principale', phone: '+237 278 72 28 92' },
  { id: '57', name: 'Agence Yaoundé Bastos', city: 'Yaoundé Bastos', region: 'Centre', address: 'Centre-ville', phone: '+237 279 09 41 99' },
  { id: '58', name: 'Agence Yaoundé Mendong', city: 'Yaoundé Mendong', region: 'Centre', address: 'Yaoundé Mendong - Avenue principale', phone: '+237 280 46 54 06' },
  { id: '59', name: 'Agence Yaoundé Nkolbisson', city: 'Yaoundé Nkolbisson', region: 'Centre', address: 'Yaoundé Nkolbisson - Avenue principale', phone: '+237 281 83 67 13' },
  { id: '60', name: 'Agence Soa', city: 'Soa', region: 'Centre', address: 'Centre-ville', phone: '+237 282 20 80 20' },
  { id: '61', name: 'Agence Mfou', city: 'Mfou', region: 'Centre', address: 'Mfou - Avenue principale', phone: '+237 283 57 93 27' },
  { id: '62', name: 'Agence Monatélé', city: 'Monatélé', region: 'Centre', address: 'Monatélé - Avenue principale', phone: '+237 284 94 06 34' },
  { id: '63', name: 'Agence Ngaoundal', city: 'Ngaoundal', region: 'Adamaoua', address: 'Centre-ville', phone: '+237 285 31 19 41' },
  { id: '64', name: 'Agence Banyo', city: 'Banyo', region: 'Adamaoua', address: 'Banyo - Avenue principale', phone: '+237 286 68 32 48' },
  { id: '65', name: 'Agence Tignère', city: 'Tignère', region: 'Adamaoua', address: 'Tignère - Avenue principale', phone: '+237 287 05 45 55' },
  { id: '66', name: 'Agence Ayos', city: 'Ayos', region: 'Centre', address: 'Centre-ville', phone: '+237 288 42 58 62' },
  { id: '67', name: 'Agence Akonolinga', city: 'Akonolinga', region: 'Centre', address: 'Akonolinga - Avenue principale', phone: '+237 289 79 71 69' },
  { id: '68', name: 'Agence Kaélé', city: 'Kaélé', region: 'Extrême-Nord', address: 'Kaélé - Avenue principale', phone: '+237 290 16 84 76' },
  { id: '69', name: 'Agence Mindif', city: 'Mindif', region: 'Extrême-Nord', address: 'Centre-ville', phone: '+237 291 53 97 83' },
  { id: '70', name: 'Agence Moulvoudaye', city: 'Moulvoudaye', region: 'Extrême-Nord', address: 'Moulvoudaye - Avenue principale', phone: '+237 292 90 10 90' },
  { id: '71', name: 'Agence Bali', city: 'Bali', region: 'Nord-Ouest', address: 'Bali - Avenue principale', phone: '+237 293 27 23 97' },
  { id: '72', name: 'Agence Santa', city: 'Santa', region: 'Nord-Ouest', address: 'Centre-ville', phone: '+237 294 64 36 04' },
  { id: '73', name: 'Agence Jakiri', city: 'Jakiri', region: 'Nord-Ouest', address: 'Jakiri - Avenue principale', phone: '+237 295 01 49 11' },
  { id: '74', name: 'Agence Nkambe', city: 'Nkambe', region: 'Nord-Ouest', address: 'Nkambe - Avenue principale', phone: '+237 296 38 62 18' },
  { id: '75', name: 'Agence Ekondo-Titi', city: 'Ekondo-Titi', region: 'Sud-Ouest', address: 'Centre-ville', phone: '+237 297 75 75 25' },
  { id: '76', name: 'Agence Isangele', city: 'Isangele', region: 'Sud-Ouest', address: 'Isangele - Avenue principale', phone: '+237 298 12 88 32' },
  { id: '77', name: 'Agence Konye', city: 'Konye', region: 'Sud-Ouest', address: 'Konye - Avenue principale', phone: '+237 299 49 01 39' },
  { id: '78', name: 'Agence Nguti', city: 'Nguti', region: 'Sud-Ouest', address: 'Centre-ville', phone: '+237 222 86 14 46' },
  { id: '79', name: 'Agence Bafang', city: 'Bafang', region: 'Ouest', address: 'Bafang - Avenue principale', phone: '+237 223 23 27 53' },
  { id: '80', name: 'Agence Massangam', city: 'Massangam', region: 'Ouest', address: 'Massangam - Avenue principale', phone: '+237 224 60 40 60' },
  { id: '81', name: 'Agence Galim', city: 'Galim', region: 'Ouest', address: 'Centre-ville', phone: '+237 225 97 53 67' },
  { id: '82', name: 'Agence Penka-Michel', city: 'Penka-Michel', region: 'Ouest', address: 'Penka-Michel - Avenue principale', phone: '+237 226 34 66 74' },
  { id: '83', name: 'Agence Melong', city: 'Melong', region: 'Littoral', address: 'Melong - Avenue principale', phone: '+237 227 71 79 81' },
  { id: '84', name: 'Agence Manjo', city: 'Manjo', region: 'Littoral', address: 'Centre-ville', phone: '+237 228 08 92 88' },
  { id: '85', name: 'Agence Njombe', city: 'Njombe', region: 'Littoral', address: 'Njombe - Avenue principale', phone: '+237 229 45 05 95' },
  { id: '86', name: 'Agence Pouma', city: 'Pouma', region: 'Littoral', address: 'Pouma - Avenue principale', phone: '+237 230 82 18 02' },
  { id: '87', name: 'Agence Ngambe', city: 'Ngambe', region: 'Littoral', address: 'Centre-ville', phone: '+237 231 19 31 09' },
  { id: '88', name: 'Agence Eseka', city: 'Eseka', region: 'Centre', address: 'Eseka - Avenue principale', phone: '+237 232 56 44 16' },
  { id: '89', name: 'Agence Boumnyebel', city: 'Boumnyebel', region: 'Centre', address: 'Boumnyebel - Avenue principale', phone: '+237 233 93 57 23' },
  { id: '90', name: 'Agence Makak', city: 'Makak', region: 'Centre', address: 'Centre-ville', phone: '+237 234 30 70 30' },
  { id: '91', name: 'Agence Djoum', city: 'Djoum', region: 'Sud', address: 'Djoum - Avenue principale', phone: '+237 235 67 83 37' },
  { id: '92', name: 'Agence Zoétélé', city: 'Zoétélé', region: 'Sud', address: 'Zoétélé - Avenue principale', phone: '+237 236 04 96 44' },
  { id: '93', name: 'Agence Meyomessala', city: 'Meyomessala', region: 'Sud', address: 'Centre-ville', phone: '+237 237 41 09 51' },
  { id: '94', name: 'Agence Olamze', city: 'Olamze', region: 'Sud', address: 'Olamze - Avenue principale', phone: '+237 238 78 22 58' },
  { id: '95', name: 'Agence Lomié', city: 'Lomié', region: 'Est', address: 'Lomié - Avenue principale', phone: '+237 239 15 35 65' },
  { id: '96', name: 'Agence Messamena', city: 'Messamena', region: 'Est', address: 'Centre-ville', phone: '+237 240 52 48 72' },
  { id: '97', name: 'Agence Doumé', city: 'Doumé', region: 'Est', address: 'Doumé - Avenue principale', phone: '+237 241 89 61 79' },
  { id: '98', name: 'Agence Nguelemendouka', city: 'Nguelemendouka', region: 'Est', address: 'Nguelemendouka - Avenue principale', phone: '+237 242 26 74 86' },
  { id: '99', name: 'Agence Bétaré-Oya', city: 'Bétaré-Oya', region: 'Est', address: 'Centre-ville', phone: '+237 243 63 87 93' },
  { id: '100', name: 'Agence Garoua-Boulaï', city: 'Garoua-Boulaï', region: 'Est', address: 'Garoua-Boulaï - Avenue principale', phone: '+237 244 00 00 00' },
  { id: '101', name: 'Agence Bankim', city: 'Bankim', region: 'Adamaoua', address: 'Bankim - Avenue principale', phone: '+237 245 37 13 07' },
  { id: '102', name: 'Agence Djohong', city: 'Djohong', region: 'Adamaoua', address: 'Centre-ville', phone: '+237 246 74 26 14' },
];