# Generated by Django 6.0.7

from django.db import connection, migrations


def create_postgres_search_indexes(apps, schema_editor):
    if connection.vendor != 'postgresql':
        return
    with connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS products_search_gin_idx
            ON products_product
            USING GIN (to_tsvector('simple', coalesce(name, '') || ' ' || coalesce(name_en, '') || ' ' || coalesce(description, '') || ' ' || coalesce(description_en, '')));
            """
        )
        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS news_search_gin_idx
            ON news_news
            USING GIN (to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(title_en, '') || ' ' || coalesce(content, '') || ' ' || coalesce(content_en, '')));
            """
        )


def drop_postgres_search_indexes(apps, schema_editor):
    if connection.vendor != 'postgresql':
        return
    with connection.cursor() as cursor:
        cursor.execute('DROP INDEX IF EXISTS products_search_gin_idx;')
        cursor.execute('DROP INDEX IF EXISTS news_search_gin_idx;')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_alter_activitylog_action_and_more'),
        ('products', '0004_product_translation_fields'),
        ('news', '0002_news_translation_fields'),
    ]

    operations = [
        migrations.RunPython(create_postgres_search_indexes, drop_postgres_search_indexes),
    ]
