# Generated by Django 6.0.7 on 2026-08-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_payment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('offer_view', 'offer_view'), ('offer_compare', 'offer_compare'), ('service_view', 'service_view'), ('product_view', 'product_view'), ('subscription_started', 'subscription_started'), ('subscription_submitted', 'subscription_submitted'), ('subscription_approved', 'subscription_approved'), ('subscription_activated', 'subscription_activated'), ('subscription_completed', 'subscription_completed'), ('payment_started', 'payment_started'), ('payment_completed', 'payment_completed'), ('search', 'search'), ('faq_view', 'faq_view'), ('chatbot_question', 'chatbot_question'), ('recommendation_clicked', 'recommendation_clicked'), ('comparison', 'comparison')], max_length=64),
        ),
    ]
