# Generated by Django 6.0.7 on 2026-08-14 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_request_numbers(apps, schema_editor):
    """Renseigne request_number sur toute ligne existante (n'impactera que des
    donnees historiques sans numero). Les nouvelles lignes sont numerotees via
    SubscriptionRequest.save()."""
    SubscriptionRequest = apps.get_model('subscriptions', 'SubscriptionRequest')
    rows = list(SubscriptionRequest.objects.filter(request_number__isnull=True).order_by('created_at'))
    for index, obj in enumerate(rows, start=1):
        # Prefixe annee + sequence stable (reutilise la logique du modele).
        year = obj.created_at.year if obj.created_at else 2026
        obj.request_number = f'SUB-{year}-{index:06d}'
        obj.save(update_fields=['request_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_activation_fee_product_availability_and_more'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, default='', max_length=40)),
                ('new_status', models.CharField(max_length=40)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='request_number',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('UNDER_REVIEW', 'En cours de traitement'), ('ADDITIONAL_INFO_REQUIRED', 'Informations complementaires requises'), ('APPROVED', 'Approuve'), ('SCHEDULED', 'Planifie'), ('ACTIVATED', 'Active'), ('REJECTED', 'Rejete'), ('CANCELLED', 'Annule')], default='PENDING', max_length=40),
        ),
        migrations.AddIndex(
            model_name='subscriptionrequest',
            index=models.Index(fields=['status'], name='subscriptio_status_c6f529_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionrequest',
            index=models.Index(fields=['user'], name='subscriptio_user_id_b98be6_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionrequest',
            index=models.Index(fields=['request_number'], name='subscriptio_request_7c9cd3_idx'),
        ),
        migrations.AddField(
            model_name='subscriptionstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionstatushistory',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='subscriptions.subscriptionrequest'),
        ),
        migrations.RunPython(
            code=backfill_request_numbers,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
