# Generated by Django 6.0.7 on 2026-08-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionstatushistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='request_number',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
