# Generated by Django 6.0.7 on 2026-08-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscriptionrequest_request_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('UNDER_REVIEW', 'En cours de traitement'), ('ADDITIONAL_INFO_REQUIRED', 'Informations complementaires requises'), ('APPROVED', 'Approuve'), ('SCHEDULED', 'Planifie'), ('ACTIVATED', 'Active'), ('REJECTED', 'Rejete'), ('CANCELLED', 'Annule'), ('DRAFT', 'Brouillon'), ('ACTIVATING', 'En cours d activation'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('COMPLETED', 'Termine')], default='PENDING', max_length=40),
        ),
    ]
