# Generated by Django 6.0.7 on 2026-08-25 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_brand_product_coverage_product_data_origin_and_more'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='promotion',
            name='last_verified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='products.product'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='source_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='promotion',
            name='source_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='promotion',
            name='status',
            field=models.CharField(choices=[('VALID', 'Valid'), ('EXPIRED', 'Expired'), ('UPCOMING', 'Upcoming'), ('REQUIRES_VERIFICATION', 'Requires verification')], default='VALID', max_length=24),
        ),
    ]
