"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#
# En production, SECRET_KEY est OBLIGATOIRE et doit etre fourni via
# l'environnement (voir settings/prod.py). En developpement uniquement une
# valeur de secours non securisee est autorisee.
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dev-only-insecure-key-not-for-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in {'1', 'true', 'yes', 'on'}

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Seed demo : active par defaut en developpement, factuellement desactive hors
# developpement (la commande seed_data refuse alors de s'executer sans option
# --force explicite ou SEED_DEMO_DATA=true).
SEED_DEMO_DATA = os.environ.get('SEED_DEMO_DATA', 'True').lower() in {'1', 'true', 'yes', 'on'}
if not DEBUG and 'SEED_DEMO_DATA' not in os.environ:
    SEED_DEMO_DATA = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',

    # 3rd party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',

    # local apps
    'apps.users',
    'apps.core',
    'apps.categories',
    'apps.products',
    'apps.news',
    'apps.promotions',
    'apps.media',
    'apps.contacts',
    'apps.subscriptions',
    'apps.partners',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'apps.core.middleware.LanguageMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.core.middleware.ActivityLogMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_NAME = os.environ.get('DB_NAME', BASE_DIR / 'db.sqlite3')
DB_USER = os.environ.get('DB_USER', '')
DB_PASSWORD = os.environ.get('DB_PASSWORD', '')
DB_HOST = os.environ.get('DB_HOST', '')
DB_PORT = os.environ.get('DB_PORT', '')

if DB_HOST:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr'

LANGUAGES = [
    ('fr', 'Français'),
    ('en', 'English'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Logging structuré JSON (activable via LOG_FORMAT=json)
LOG_FORMAT = os.environ.get('LOG_FORMAT', 'text')

_log_formatters = {
    'verbose': {
        'format': '{levelname} {asctime} {module} {message}',
        'style': '{',
    },
}

try:
    import pythonjsonlogger  # noqa: F401
    _log_formatters['json'] = {
        '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
        'format': '%(asctime)s %(levelname)s %(name)s %(message)s',
    }
    _console_formatter = 'json' if LOG_FORMAT == 'json' else 'verbose'
except ImportError:
    _console_formatter = 'verbose'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': _log_formatters,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': _console_formatter,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.environ.get('LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# Django REST Framework
REST_FRAMEWORK = {
    # Order matters: the FIRST authenticator provides the WWW-Authenticate
    # header DRF uses to decide between 401 and 403 on failed auth.
    # SessionAuthentication defines no such header -> would coerce to 403.
    # JWT first => anonymous writes get a proper 401 (API contract + tests);
    # session auth still works for the Django admin / back-office.
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.environ.get('THROTTLE_ANON_RATE', '60/min'),
        'user': os.environ.get('THROTTLE_USER_RATE', '600/min'),
        'login': '5/min',
        'register': '3/hour',
        'auth': '20/min',
        'chatbot': '30/min',
        'search': '120/min',
        'contact': '5/hour',
        'partner': os.environ.get('THROTTLE_PARTNER_RATE', '1000/hour'),
    },
}

# SimpleJWT — rotation du refresh + blacklist (revocation effective au logout)
from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.environ.get('JWT_ACCESS_LIFETIME_MINUTES', 30))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.environ.get('JWT_REFRESH_LIFETIME_DAYS', 7))),
    # Rotation active : chaque refresh emet un nouveau refresh token et
    # blackliste l'ancien (vol de token = fenetre d'usage unique).
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'BLACKLIST_TOKEN_CHECKS': ['rest_framework_simplejwt.utils.check_blacklist'],
}

# ---------------------------------------------------------------------------
# Refresh token — cookie HttpOnly (PHASE Securite)
# ---------------------------------------------------------------------------
# Le refresh token n'est plus jamais renvoye dans le corps JSON ni stocke en
# localStorage cote SPA (risque XSS). Il est pose par le backend comme cookie
# HttpOnly, scope au prefixe /api/v1/auth/ (seuls /refresh/ et /logout/ en ont
# besoin), non lisible en JS. L'access token (courte duree) reste renvoye dans
# le corps de la reponse et gere par le frontend (memoire/localStorage).
REFRESH_COOKIE_NAME = os.environ.get('REFRESH_COOKIE_NAME', 'camtel_refresh')
REFRESH_COOKIE_PATH = '/api/v1/auth/'
REFRESH_COOKIE_SECURE = os.environ.get('REFRESH_COOKIE_SECURE', 'False').lower() in {'1', 'true', 'yes', 'on'}
# 'Lax' suffit pour des appels XHR/fetch same-site (le cas normal d'une SPA
# servie sur le meme domaine ou un sous-domaine avec CORS_ALLOW_CREDENTIALS) ;
# passer a 'None' (+ Secure obligatoire) uniquement si frontend et backend
# sont sur des domaines strictement differents en production.
REFRESH_COOKIE_SAMESITE = os.environ.get('REFRESH_COOKIE_SAMESITE', 'Lax')
REFRESH_COOKIE_MAX_AGE = int(timedelta(days=int(os.environ.get('JWT_REFRESH_LIFETIME_DAYS', 7))).total_seconds())

# Les cookies HttpOnly etant envoyes automatiquement par le navigateur, le
# frontend doit faire ses requetes avec `credentials`/`withCredentials`, et le
# backend doit repondre avec Access-Control-Allow-Credentials.
CORS_ALLOW_CREDENTIALS = True

SPECTACULAR_SETTINGS = {
    'TITLE': 'CAMTEL OnePortal API',
    'DESCRIPTION': 'API backend de la plateforme CAMTEL OnePortal.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': r'/api/v1/',
    'TAGS': [
        {'name': 'Partner API', 'description': 'Endpoints partenaires (clé API X-API-Key, scopes limités).'},
    ],
}

# CORS — en developpement on autorise tout par defaut, mais on peut restreindre
# via l'environnement (CORS_ALLOW_ALL_ORIGINS / CORS_ALLOWED_ORIGINS). La
# configuration de production (settings/prod.py) force une liste blanche stricte.
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'True').lower() in {'1', 'true', 'yes', 'on'}
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
    if origin.strip()
]
CORS_URLS_REGEX = r'^/api/.*$'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# ---------------------------------------------------------------------------
# OnePortal AI — Chatbot / RAG / LLM (V2)
# ---------------------------------------------------------------------------
# CHATBOT_PROVIDER:  "none" | "mock" | "gemini" | "openai" | "ollama"
#   - "none"      : comportement actuel (recherche textuelle FAQ + produits)
#   - "mock"      : repond avec des reponses factices (dev/test)
#   - "gemini"    : Google Gemini (requiert google-generativeai + GOOGLE_API_KEY)
#   - "openai"    : OpenAI (requiert openai + OPENAI_API_KEY)
#   - "ollama"    : LLM local via Ollama (requiert ollama + serveur demarre)
CHATBOT_ENABLED = os.environ.get('CHATBOT_ENABLED', 'True').lower() in {'1', 'true', 'yes', 'on'}
CHATBOT_PROVIDER = os.environ.get('CHATBOT_PROVIDER', 'none')
CHATBOT_MODEL = os.environ.get('CHATBOT_MODEL', None)
CHATBOT_TEMPERATURE = float(os.environ.get('CHATBOT_TEMPERATURE', '0.3'))
CHATBOT_MAX_TOKENS = int(os.environ.get('CHATBOT_MAX_TOKENS', '512'))
# Delai maximum (secondes) accorde a l'appel LLM avant abandon. Sans cette
# limite, un provider qui ne repond pas (reseau lent, quota, panne cote
# fournisseur) bloque le thread de la requete indefiniment — constate en
# conditions reelles : le SDK google-generativeai utilise gRPC, qui peut
# retenter une connexion pendant plusieurs minutes sans jamais lever
# d'exception si la connexion TLS echoue silencieusement en boucle. Cote
# utilisateur, ca se traduit par un chat qui reste bloque sur "en train
# d'ecrire..." sans fin plutot que par un message d'erreur propre.
CHATBOT_TIMEOUT_SECONDS = int(os.environ.get('CHATBOT_TIMEOUT_SECONDS', '20'))
CHATBOT_FALLBACK_TO_SEARCH = os.environ.get('CHATBOT_FALLBACK_TO_SEARCH', 'True').lower() in {'1', 'true', 'yes', 'on'}
CHATBOT_SYSTEM_PROMPT = os.environ.get(
    'CHATBOT_SYSTEM_PROMPT',
    "Tu es OnePortal AI, l'assistant CAMTEL. Reponds en francais, de façon concise et "
    "exacte, uniquement a partir du contexte fourni. Si tu ne connais pas la reponse, "
    "dis-le clairement.",
)
CHATBOT_RATE_LIMIT = float(os.environ.get('CHATBOT_RATE_LIMIT', '0.0'))

# Cles API LLM (optionnelles — lues aussi via env dans les providers)
GOOGLE_API_KEY = os.environ.get('GOOGLE_API_KEY', None)
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', None)
OLLAMA_BASE_URL = os.environ.get('OLLAMA_BASE_URL', 'http://localhost:11434')

# ---------------------------------------------------------------------------
# Services V2 — abstractions sans faux connecteurs externes
# ---------------------------------------------------------------------------
PAYMENT_PROVIDER = os.environ.get('PAYMENT_PROVIDER', 'mock')
# Orange Money
ORANGE_MONEY_CLIENT_ID = os.environ.get('ORANGE_MONEY_CLIENT_ID', '')
ORANGE_MONEY_CLIENT_SECRET = os.environ.get('ORANGE_MONEY_CLIENT_SECRET', '')
ORANGE_MONEY_BASE_URL = os.environ.get('ORANGE_MONEY_BASE_URL', 'https://api.orange.com')
ORANGE_MONEY_MERCHANT_KEY = os.environ.get('ORANGE_MONEY_MERCHANT_KEY', '')
ORANGE_MONEY_RETURN_URL = os.environ.get('ORANGE_MONEY_RETURN_URL', '')
ORANGE_MONEY_CANCEL_URL = os.environ.get('ORANGE_MONEY_CANCEL_URL', '')
ORANGE_MONEY_NOTIF_URL = os.environ.get('ORANGE_MONEY_NOTIF_URL', '')
# MTN MoMo
MTN_MOMO_SUBSCRIPTION_KEY = os.environ.get('MTN_MOMO_SUBSCRIPTION_KEY', '')
MTN_MOMO_API_USER = os.environ.get('MTN_MOMO_API_USER', '')
MTN_MOMO_API_KEY = os.environ.get('MTN_MOMO_API_KEY', '')
MTN_MOMO_BASE_URL = os.environ.get('MTN_MOMO_BASE_URL', 'https://sandbox.momodeveloper.mtn.com')
MTN_MOMO_TARGET_ENVIRONMENT = os.environ.get('MTN_MOMO_TARGET_ENVIRONMENT', 'sandbox')
MTN_MOMO_CALLBACK_URL = os.environ.get('MTN_MOMO_CALLBACK_URL', '')
PAYMENT_TIMEOUT_SECONDS = int(os.environ.get('PAYMENT_TIMEOUT_SECONDS', '15'))
ELIGIBILITY_PROVIDER = os.environ.get('ELIGIBILITY_PROVIDER', 'mock')
# Data freshness (#34) : une offre OFFICIAL non reverifiee depuis N jours est STALE.
DATA_FRESHNESS_DAYS = int(os.environ.get('DATA_FRESHNESS_DAYS', '30'))
# URL optionnelle de l'API officielle Fiber Connect pour l'eligibilite reelle.
CAMTEL_FIBER_ELIGIBILITY_URL = os.environ.get('CAMTEL_FIBER_ELIGIBILITY_URL', '')
EMAIL_PROVIDER = os.environ.get('EMAIL_PROVIDER', 'console')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@oneportal.local')
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')

# Celery configuration (optional). Set USE_CELERY=true and provide a broker
# (e.g. redis://localhost:6379/0) in production.
USE_CELERY = os.environ.get('USE_CELERY', 'False').lower() in {'1', 'true', 'yes', 'on'}
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
# For local smoke-tests without a broker, allow tasks to run eagerly.
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', 'False').lower() in {'1', 'true', 'yes', 'on'}

# DocumentStore local : liste de documents/CGV/guides prête pour exposition API
# et ingestion RAG. Peut être remplacée en V3 par une GED/S3/index vectoriel.
DOCUMENT_STORE = [
    {
        'id': 'cgv-internet',
        'kind': 'terms',
        'title': 'Conditions générales des offres Internet CAMTEL',
        'summary': 'Conditions de souscription, installation, facturation et résiliation des offres Internet.',
        'url': '/media/documents/cgv-internet.pdf',
        'tags': ['internet', 'fibre', 'cgv'],
        'product_id': None,
    },
    {
        'id': 'guide-souscription',
        'kind': 'guide',
        'title': 'Guide de souscription OnePortal',
        'summary': 'Étapes de demande, validation, planification et activation du service.',
        'url': '/media/documents/guide-souscription.pdf',
        'tags': ['souscription', 'activation', 'support'],
        'product_id': None,
    },
]
