# Generated by Django 6.0.7 on 2026-08-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_segment'),
        ('products', '0005_alter_productimage_options_productimage_is_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='activation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('ALL', 'All regions'), ('REGION', 'Region specific'), ('ADDRESS_CHECK', 'Address check required')], default='ALL', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='billing_period',
            field=models.CharField(choices=[('ONE_TIME', 'One time'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='contract_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Engagement en mois (null = sans engagement)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='XAF', max_length=8),
        ),
        migrations.AddField(
            model_name='product',
            name='eligibility',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='installation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_type',
            field=models.CharField(choices=[('INTERNET', 'Internet'), ('FIBER', 'Fiber'), ('MOBILE', 'Mobile'), ('VOICE', 'Voice'), ('DATA', 'Data'), ('CLOUD', 'Cloud'), ('HOSTING', 'Hosting'), ('VPN', 'VPN'), ('EQUIPMENT', 'Equipment'), ('BUSINESS_SOLUTION', 'Business solution'), ('OTHER', 'Other')], default='OTHER', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('SERVICE_OFFER', 'Service offer'), ('PHYSICAL_PRODUCT', 'Physical product')], default='SERVICE_OFFER', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='segment',
            field=models.CharField(choices=[('PARTICULIER', 'Particulier'), ('PROFESSIONNEL', 'Professionnel'), ('ENTREPRISE', 'Entreprise'), ('ADMINISTRATION', 'Administration')], default='PARTICULIER', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='technology',
            field=models.CharField(choices=[('FTTH', 'Fiber to the Home'), ('FTTB', 'Fiber to the Building'), ('ADSL', 'ADSL'), ('LTE', 'LTE/4G'), ('5G', '5G'), ('DEDICATED', 'Dedicated link'), ('OTHER', 'Other')], default='OTHER', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['offer_type'], name='products_pr_offer_t_a7fb66_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['segment'], name='products_pr_segment_fca6f4_idx'),
        ),
    ]
