# Generated by Django 6.0.7 on 2026-08-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_populate_product_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('CAMTEL', 'CAMTEL'), ('BLUE', 'Blue'), ('FIBER_CONNECT', 'Fiber Connect'), ('HOSTING', 'CAMTEL Hosting'), ('CARRIER', 'CAMTEL Carrier')], default='CAMTEL', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='coverage',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='data_origin',
            field=models.CharField(choices=[('OFFICIAL', 'Official CAMTEL source'), ('DEMO', 'Demo data'), ('MANUAL', 'Manual entry')], default='MANUAL', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='data_volume',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='last_verified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_type',
            field=models.CharField(choices=[('FIXED', 'Fixed price'), ('QUOTE', 'Price on request (quote)'), ('FREE', 'Free')], default='FIXED', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='service_type',
            field=models.CharField(choices=[('OFFER', 'Offer'), ('SERVICE', 'Service'), ('PRODUCT', 'Product')], default='OFFER', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='sms_volume',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='source_checked_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='source_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='source_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='source_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='speed',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('VALID', 'Valid'), ('EXPIRED', 'Expired'), ('UPCOMING', 'Upcoming'), ('REQUIRES_VERIFICATION', 'Requires verification')], default='VALID', max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, default='', help_text='Sous-famille officielle (ex: CB VPS, CB Rack Housing)', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='subscription_method',
            field=models.CharField(blank=True, choices=[('ONLINE', 'Online'), ('AGENCY', 'Agency / sales point'), ('USSD', 'USSD'), ('MOBILE_APP', 'Mobile app'), ('CONTACT', 'Contact / quote')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='ussd_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='validity',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='voice_volume',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Prix annuel lorsque la source officielle le publie.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='activation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='installation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
    ]
