# Generated by Django 6.0.7 on 2026-08-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_brand_product_coverage_product_data_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='original_source_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
