# Generated by Django 6.0.7 on 2026-08-28 09:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_segment'),
        ('products', '0010_productimage_original_source_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('code', models.CharField(choices=[('PARTICULIER', 'Particulier'), ('PROFESSIONNEL', 'Professionnel'), ('ENTREPRISE', 'Entreprise'), ('ADMINISTRATION', 'Administration')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('name_en', models.CharField(blank=True, default='', max_length=128)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SourceVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.CharField(choices=[('VERIFIED', 'Verified'), ('CHANGED', 'Content changed'), ('UNAVAILABLE', 'Source unavailable'), ('INVALID', 'Invalid / rejected')], default='VERIFIED', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-verified_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='historical_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_origin',
            field=models.CharField(choices=[('OFFICIAL', 'Official CAMTEL source'), ('DEMO', 'Demo data'), ('MANUAL', 'Manual entry'), ('HISTORICAL', 'Historical data'), ('MOCK', 'Mock / simulated data'), ('REQUIRES_VALIDATION', 'Requires business validation')], default='MANUAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='pricing_type',
            field=models.CharField(choices=[('FIXED', 'Fixed price (FIXED_PRICE)'), ('QUOTE', 'Price on request (quote)'), ('FREE', 'Free'), ('INSTALLATION', 'Installation fee'), ('USAGE_BASED', 'Usage based')], default='FIXED', max_length=16),
        ),
        migrations.CreateModel(
            name='ProductSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True, default='')),
                ('source_type', models.CharField(choices=[('OFFICIAL_WEBSITE', 'Official website'), ('OFFICIAL_DOCUMENT', 'Official document'), ('SNAPSHOT', 'Catalog snapshot'), ('AGENCY', 'Agency / sales point'), ('SUPPORT', 'Support channel'), ('OTHER', 'Other')], default='OFFICIAL_WEBSITE', max_length=32)),
                ('verification_status', models.CharField(choices=[('OFFICIAL', 'Official'), ('MANUAL', 'Manual'), ('HISTORICAL', 'Historical'), ('DEMO', 'Demo'), ('MOCK', 'Mock'), ('REQUIRES_VALIDATION', 'Requires validation')], default='REQUIRES_VALIDATION', max_length=32)),
                ('last_verified_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sources', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='products.product')),
            ],
            options={
                'ordering': ['-is_primary', '-last_verified_at', 'source_name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='segments',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.segment'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('code', models.CharField(choices=[('FIXED', 'Fixes'), ('MOBILE', 'Mobiles'), ('TRANSPORT', 'Transport'), ('DATA_CENTER', 'Data Center')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('name_en', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['status'], name='products_se_status_1dc37a_idx')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.service'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['service'], name='products_pr_service_c08996_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['data_origin'], name='products_pr_data_or_ae111f_idx'),
        ),
        migrations.AddField(
            model_name='sourceverificationlog',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='products.productsource'),
        ),
        migrations.AddField(
            model_name='sourceverificationlog',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='productsource',
            index=models.Index(fields=['verification_status'], name='products_pr_verific_d1106e_idx'),
        ),
        migrations.AddIndex(
            model_name='productsource',
            index=models.Index(fields=['product', 'is_primary'], name='products_pr_product_c17822_idx'),
        ),
        migrations.AddConstraint(
            model_name='productsource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verification_status', 'OFFICIAL'), _negated=True), models.Q(('source_url', ''), _negated=True), _connector='OR'), name='productsource_official_requires_url'),
        ),
        migrations.AddIndex(
            model_name='sourceverificationlog',
            index=models.Index(fields=['source', 'verified_at'], name='products_so_source__0be61f_idx'),
        ),
    ]
